name: Build & Deploy to Production

# Run when a dispatch event is created (e.g. from a CMS Webhook)
# See https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
on: 
  [repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v1 # Equivalent to `git checkout master`
    
        - name: Setup Node
          uses: actions/setup-node@v1.4.2
          with:
              node-version: '14.x'

        - name: install dependencies
          run: npm install
        
        - name: Deploy
          run: npm run deploy
          env: 
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
            CONTENTFUL_ACCESS_KEY: ${{ secrets.CONTENTFUL_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
